apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  jwtPrivateKey: {{ .Values.secrets.jwtPrivateKey | quote }}
  jwtPublicKey: {{ .Values.secrets.jwtPublicKey | quote }}
