[mypy]
python_version = 3.11
strict = True
warn_unused_configs = True
plugins = pydantic.mypy
mypy_path = .

[mypy-tests.*]
disallow_untyped_defs = False

[mypy-celery.*]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-src.workers.*]
ignore_errors = True
